// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qonjtrhwkxvozqukqajb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvbmp0cmh3a3h2b3pxdWtxYWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5ODU0ODQsImV4cCI6MjA3MTU2MTQ4NH0.hPqL9x8i8EeLdKYLYF8VS86IThig9UsZpQI17ZqHgwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});